# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 2
repository: <DockerImagesRepositoryURL>
imagesTag: <DockerImagesTag>

global:
    DATABRICKS_WORKSPACE_URL: <DATABRICKS_WORKSPACE_URL>
    APP_INSIGHTS_INSTRUMENTATION_KEY: <APP_INSIGHTS_INSTRUMENTATION_KEY>
    secret:
        DATABRICKS_AUTH_TOKEN: <DATABRICKS_AUTH_TOKEN>

prediction:
    name: prediction
    dockerImage: 
        name: prediction
    TRAINING_SERVICE_API_TRAIN_PATH: /train
    TRAINING_REQUESTS_TIMEOUT: 1000
    
modelRunner:
    dockerImage: 
        name: model-runner
    MLFLOW_SERVER_API_PREFIX: /api/2.0/mlflow
    MLFLOW_SERVER_SEARCH_PATH: /runs/search
    MODELS_RELATIVE_PATH: model
    MLFLOW_REQUESTS_TIMEOUT: 1000
    MLFlowModels:
        1: 
            MODEL_NAME: WINE
            EXPERIMENT_ID: <MLFLOW_EXPERIMENT_ID>
        2: 
            MODEL_NAME: DIABETES
            EXPERIMENT_ID: <MLFLOW_EXPERIMENT_ID>
    
training:
    name: training
    dockerImage: 
        name: training
    DATABRICKS_CLUSTER_ID: <DATABRICKS_CLUSTER_ID>
    DATABRICKS_RUN_TIMEOUT: 3600
    DATABRICKS_TYPE_MAPPING: <JSON represents ModelName => NotebookPath in Databricks> 
    #e.g: DATABRICKS_TYPE_MAPPING: '{"wine":"/shared/wine_notebook","diabetes":"/shared/diabetes_notebook"}' 
    