{{- range $key, $value := .Values.modelRunner.MLFlowModels }}
{{ $modelName := $value.MODEL_NAME | lower }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $modelName }}-service
spec:
  selector:
    app: {{ $modelName }}
    tier: backend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
{{- end }}