{{ $replicas := .Values.replicas }}
{{ $image := printf "%s/%s:%s" .Values.repository .Values.modelRunner.dockerImage.name .Values.imagesTag }}

{{- range $key, $value := .Values.modelRunner.MLFlowModels }}
{{ $modelName := $value.MODEL_NAME | lower }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $modelName }}
spec:
  selector:
    matchLabels:
      app: {{ $modelName }}
      tier: backend
  replicas: {{ $replicas }}
  template:
    metadata:
      labels:
        app: {{ $modelName }}
        tier: backend
    spec:
      containers:
        - name: {{ $modelName }}
          image: {{ $image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          env:
            - name: SERVICE_NAME
              value: {{ $modelName }}-service
            - name: MLFLOW_SERVER_API_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: {{ $modelName }}-config
                  key: MLFLOW_SERVER_API_PREFIX
            - name: MLFLOW_SERVER_SEARCH_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ $modelName }}-config
                  key: MLFLOW_SERVER_SEARCH_PATH
            - name: MLFLOW_EXPERIMENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ $modelName }}-config
                  key: MLFLOW_EXPERIMENT_ID
            - name: MLFLOW_REQUESTS_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ $modelName }}-config
                  key: MLFLOW_REQUESTS_TIMEOUT
            - name: MODELS_RELATIVE_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ $modelName }}-config
                  key: MODELS_RELATIVE_PATH
            - name: MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ $modelName }}-config
                  key: MODEL_NAME
            - name: APP_INSIGHTS_INSTRUMENTATION_KEY
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: APP_INSIGHTS_INSTRUMENTATION_KEY
            - name: DATABRICKS_HOST
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: DATABRICKS_WORKSPACE_URL
            - name: DATABRICKS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: DATABRICKS_AUTH_TOKEN
---
{{- end }}