apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prediction.name }}-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.prediction.name }}
    tier: backend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
